---
- name: load package list variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: install host-specific programs
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ host_pkgs }}"

- name: remove programs
  package:
    name: "{{ item }}"
    state: absent
  with_items: "{{ pkgs_remove }}"
  
- name: install programs
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ pkgs }}"

- name: install programs without recommended packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 1800
    install_recommends: no
  with_items: "{{ pkgs_without_recommends }}"
  when: ansible_os_family == "Debian"

- name: install extra programs
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ pkgs_extra }}"
  when: install_extra

- meta: flush_handlers
